### ISSUE TITLE
Get started page - Line break fix (Tugboat link)

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system-site#105]
Fix weird break after the word `email`.

![IMG_0864](https://user-images.githubusercontent.com/45767595/96508934-2d141680-1210-11eb-9991-48afd1151ee0.PNG)

**Comment by dcaryll** [comment]
Fixing in https://github.com/RedHat-UX/red-hat-design-system-site/tree/10-20-20-bug-fixes
