### ISSUE TITLE
Card page - Fix padding amount (Tugboat link)

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system-site#107]
Add more padding above the `Content` section to match the padding above the `Grouping` section.

<img width="1121" alt="Screen Shot 2020-10-19 at 1 43 50 PM" src="https://user-images.githubusercontent.com/45767595/96509639-2df97800-1211-11eb-946d-f8a9e2a24dff.png">

**Comment by dcaryll** [comment]
Fixing in #118
