### ISSUE TITLE
Accordion page - Fix padding amount (Tugboat link)

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system-site#108]
Add more padding above the `Label formatting` section to match the padding above the `Content area` section.

<img width="1039" alt="Screen Shot 2020-10-19 at 1 47 10 PM" src="https://user-images.githubusercontent.com/45767595/96509931-a06a5800-1211-11eb-828f-5448f893fb87.png">

**Comment by dcaryll** [comment]
Fixing in #118
