### ISSUE TITLE
Grid page - Images are wrong sizes (Tugboat link)

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system-site#109]
The second image looks like it's 50% smaller than it should be. These images are highlighted (blue).

<img width="1041" alt="Screen Shot 2020-10-19 at 5 00 16 PM" src="https://user-images.githubusercontent.com/45767595/96524255-94d85a80-122c-11eb-8a86-4ddb7f7db3cd.png">

- - -

This second image, too.

<img width="1028" alt="Screen Shot 2020-10-19 at 5 01 24 PM" src="https://user-images.githubusercontent.com/45767595/96524305-bd605480-122c-11eb-827d-926290ef9ebb.png">

- - -

This second image as well.

<img width="1034" alt="Screen Shot 2020-10-19 at 5 01 55 PM" src="https://user-images.githubusercontent.com/45767595/96524330-cf41f780-122c-11eb-9e54-d47a96aa2bf4.png">

- - -

And these.

<img width="741" alt="Screen Shot 2020-10-19 at 5 04 29 PM" src="https://user-images.githubusercontent.com/45767595/96524449-2ea00780-122d-11eb-9c44-bbc49366ac25.png">

**Comment by dcaryll** [comment]
Fixing in #118
