### ISSUE TITLE
Design 404 page

### ISSUE THREAD

**Issue by dcaryll** [RedHat-UX/red-hat-design-system-site#127]
Design and build a custom 404 page. 

Current 404 page: https://ux.redhat.com/404

**Comment by coreyvickery** [comment]
@dcaryll @wesruv 

Here's a draft of the 404 page design, the content has not been reviewed by anyone yet.

https://xd.adobe.com/view/7306200c-7e8a-48a5-bbe4-45b355322ee0-2655/

**Comment by dcaryll** [comment]
Published new 404 page
