### ISSUE TITLE
Create image for Foundations page for spacing

### ISSUE THREAD

**Issue by dcaryll** [RedHat-UX/red-hat-design-system-site#132]
Now that we have the new Spacing page, we need to represent it on the main Foundations page. To do so, we need and image and text to link from.

**Comment by coreyvickery** [comment]
@dcaryll 

I created a new image for the Spacing page and I updated the images of the other sections to be a bit taller.

https://xd.adobe.com/view/ae261677-7a75-49b6-a7cb-b7410e8668a9-fb75/

**Comment by dcaryll** [comment]
Images added
