### ISSUE TITLE
Standardize cross-links on component pages

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system-site#146]
<img width="997" alt="Screen Shot 2021-04-21 at 2 21 48 PM" src="https://user-images.githubusercontent.com/45767595/115602438-eed5dd80-a2ac-11eb-96ce-916a72a3397d.png">

Rethinking these cross-links at the bottom of each component page, are they valuable enough given our VOC conversation on 4/21? Do we need to standardize one or both of them? For example, could the right cross-link have a link to a contact page or future survey?

**Comment by eohammond** [comment]
The link to github is convenient for us, but maybe not to all users. I'm going to look into some other options.

**Comment by eohammond** [comment]
We talked about adding User Snap this AM. If we can do that and if people use it we'll have a good solution to this. I feel like the github link is useful as well.

**Comment by coreyvickery** [comment]
I am working to standardize cross-links as I update each page.
