### ISSUE TITLE
Component status table broken in some browsers

### ISSUE THREAD

**Issue by coreyvickery** [RedHat-UX/red-hat-design-system-site#184]
When some pages are viewed in Safari or other non-Chrome browsers, the Component status table does not appear.

<img width="1413" alt="Screen Shot 2021-08-12 at 11 39 07 AM" src="https://user-images.githubusercontent.com/45767595/129250823-0da3c1d2-3885-4632-9278-8d4d63bb9f13.png">

Can this issue somehow be looked into? Should we switch to using hard code?

**Comment by kylebuch8** [comment]
This was fixed by commit d96e7ffd463a661ab8b42736e2b76aaa9a06d744.
