### ISSUE TITLE
Mobile Navigation Setup

### ISSUE THREAD

**Issue by wesruv** [RedHat-UX/red-hat-design-system-site#2]
The mobile navigation needs implemented.
@coreyvickery please add navigation specs here.

**Comment by coreyvickery** [comment]
# Navigation bar

## Desktop

### Navigation bar
<img width="800" alt="Navigation, desktop" src="https://user-images.githubusercontent.com/45767595/92077480-5f0d0e80-ed71-11ea-8d66-65ccbd610157.png">

### Spacing
<img width="800" alt="Navigation, desktop, spacing" src="https://user-images.githubusercontent.com/45767595/92077631-aa272180-ed71-11ea-821a-3fef3964a807.png">

[Download Red Hat logo](https://www.dropbox.com/s/cp1x1yvaj7e8w7g/Red-Hat-Logo-Reverse.svg?dl=0)

### Breakpoints

Device | Window | Range
------------ | ------------- | -------------
Desktop | Large | >1368px
Desktop | Small | 1200 - 1367px

## Tablet and Mobile

### Tablet, menu collapsed
<img width="768" alt="Navigation, tablet, menu collapsed" src="https://user-images.githubusercontent.com/45767595/92089584-35f57980-ed83-11ea-89a0-c566a06f2aa4.png">

### Mobile, menu collapsed
<img width="360" alt="Navigation, mobile, menu collapsed" src="https://user-images.githubusercontent.com/45767595/92077757-e35f9180-ed71-11ea-965b-19dd29834af5.png">

### Spacing, menu collapsed
<img width="360" alt="Navigation, mobile, menu collapsed, spacing" src="https://user-images.githubusercontent.com/45767595/92078315-ead36a80-ed72-11ea-854f-cd4a36d3ab6d.png">

[Download menu icon SVG](https://www.dropbox.com/s/kmkoyctjqo8fizt/Mobile-Menu.svg?dl=0)

### Tablet, menu expanded
<img width="768" alt="Navigation, tablet, menu expanded" src="https://user-images.githubusercontent.com/45767595/92089677-54f40b80-ed83-11ea-8391-03895fa7f3da.png">

### Mobile, menu expanded
<img width="360" alt="Navigation, mobile, menu expanded" src="https://user-images.githubusercontent.com/45767595/92077763-e65a8200-ed71-11ea-9a43-085c79f633ca.png">

### Spacing, menu expanded
<img width="360" alt="Navigation, mobile, menu expanded, spacing" src="https://user-images.githubusercontent.com/45767595/92078330-f161e200-ed72-11ea-97a3-87f12ae02a8d.png">

[Download close icon SVG](https://www.dropbox.com/s/ke94u8ixgs0eb7v/Mobile-Menu-Close.svg?dl=0)

### Breakpoints

Device | Window | Range
------------ | ------------- | -------------
Tablet | Landscape | 992 - 1199px
Tablet | Portrait | 768 - 991px
Mobile | Landscape | 576 - 767px
Mobile | Portrait | 320 - 575px

- - -

# Side menu

## Desktop
<img width="1440" alt="Side menu desktop" src="https://user-images.githubusercontent.com/45767595/92081855-93d09400-ed78-11ea-9bad-1c697030fad9.png">

- The side menu is always visible on large screens wider than 1200px
- The side menu default when a user lands on a page is always show all sections collapsed

## Tablet, collapsed
<img width="1440" alt="Side menu, tablet, collapsed" src="https://user-images.githubusercontent.com/45767595/92082168-0e99af00-ed79-11ea-94b9-2ee3fb37bc4c.png">

- The side menu default is collapsed on screens less than 1199px wide
- A `Hamburger` icon is visible when the menu is collapsed; a user tapping it would expand the menu, changing it to a `Close` icon

## Tablet, expanded
<img width="1440" alt="Side menu, tablet, expanded" src="https://user-images.githubusercontent.com/45767595/92082206-178a8080-ed79-11ea-8bcb-a5254e4b509e.png">

- When a user lands on a page and the side menu loads for the first time, all sections should be collapsed
- A `Close` icon is visible when the menu is expanded; a user tapping it would collapse the menu, changing it to a `Hamburger` icon
- Overlay color: #151515
- Overlay opacity: 50%

## Mobile, collapsed
<img width="1440" alt="Side menu, mobile, collapsed" src="https://user-images.githubusercontent.com/45767595/92082666-b31bf100-ed79-11ea-94b0-616f64a99eb1.png">

- A `Hamburger` icon is visible when the menu is collapsed; a user tapping it would expand the menu, changing it to a `Close` icon

## Mobile, expanded
<img width="1440" alt="Side menu, mobile, expanded" src="https://user-images.githubusercontent.com/45767595/92082678-b7e0a500-ed79-11ea-8fc4-67c342de702a.png">

- When a user lands on a page and the side menu loads for the first time, all sections should be collapsed
- A `Close` icon is visible when the menu is expanded; a user tapping it would collapse the menu, changing it to a `Hamburger` icon
- The side menu should never exceed the width of even the smallest mobile screens
- Overlay color: #151515
- Overlay opacity: 50%

- - -

# Behavior

## Desktop

- The side menu remains the same width on all large screen sizes
- A user should be able to expand sections (*Foundations* and *Components*) and scroll through links (*Overview*, *Accordion*, *Alert*, etc.) on the same screen without being directed to another page
- The side menu is persistent and a user should be able to scroll independently of page content ([Example](https://www.carbondesignsystem.com/components/accordion/usage))

## Tablet and Mobile

- Same behaviors as Desktop
- Page content underneath overlay still scrolls if a user scrolls in the overlay and not in the side menu ([Example](https://www.carbondesignsystem.com/components/accordion/usage), view at small screen size)

## Accessibility

- In addition to the close icon, **tapping** anywhere in the overlay should collapse the menu; however, a user should still be able to scroll through page content if they choose
- The overlay should cover all elements below the navigation bar, including the *Back to top* button
- When the side menu is expanded, tapping a link will direct a user to another page; when they arrive on that page, the menu should be collapsed

**Comment by coreyvickery** [comment]
@wesruv @dcaryll Let me know if I missed anything.

**Comment by wesruv** [comment]
MVP is up, it's a no-JS version of the mobile menu, it's missing a lot of things, but does have basic functionality. I'll swing back and add the JS version on top which will provide the rest of the functionality needed.

**Comment by coreyvickery** [comment]
@wesruv I have no changes to how the mobile nav looks now. We may want to revisit the design again at a later date, but I can create a new issue for that. Can we close this?

**Comment by wesruv** [comment]
Aye!
