### ISSUE TITLE
Large monitor experience

### ISSUE THREAD

**Issue by castastrophe** [RedHat-UX/red-hat-design-system-site#66]
Absolutely LOVE the new page!  The design is gorgeous and it's very well architected and laid out.

On a larger monitor, there's a lot of empty space and I wanted to raise the idea that we could use more of the space or align the content such that it doesn't leave such a large white space on the right:

<img width="2560" alt="Screen Shot 2020-10-07 at 8 46 48 AM" src="https://user-images.githubusercontent.com/1840295/95332691-c854d580-0879-11eb-8a15-f0ca1c06ccaf.png">

Happy to brainstorm if you like!

**Comment by dcaryll** [comment]
This looks like a duplicate to #67 so closing!
