### ISSUE TITLE
Tooltip - image export

### ISSUE THREAD

**Issue by eohammond** [RedHat-UX/red-hat-design-system-site#71]
Font issues in 2nd image under Best practices and both images under Behavior, image under Small Screens, Interaction states. 
![image](https://user-images.githubusercontent.com/57179912/95452710-ae79c800-0937-11eb-9321-04cc727f7b3b.png)

![image](https://user-images.githubusercontent.com/57179912/95452735-b9ccf380-0937-11eb-92e9-fad9c79264dc.png)

![image](https://user-images.githubusercontent.com/57179912/95452764-c3eef200-0937-11eb-8eb1-7d1e3d0ca163.png)

![image](https://user-images.githubusercontent.com/57179912/95452784-cb160000-0937-11eb-8580-d797301ce38a.png)

**Comment by coreyvickery** [comment]
Pull request created.

**Comment by coreyvickery** [comment]
These images were not fixed in the most recent Tugboat link. Closing this issue and creating a new issue.
