### ISSUE TITLE
Color page - image export

### ISSUE THREAD

**Issue by eohammond** [RedHat-UX/red-hat-design-system-site#72]
First two images reported as needing re-export:

First image has font issues:
![image](https://user-images.githubusercontent.com/57179912/95452889-f3056380-0937-11eb-93f9-8797d45ddd94.png)

I don't see font issues in second image:
![image](https://user-images.githubusercontent.com/57179912/95453039-2c3dd380-0938-11eb-8e9d-92ef0e1dc83f.png)

**Comment by coreyvickery** [comment]
Pull request created.

**Comment by coreyvickery** [comment]
Looks like this was fixed in the most recent Tugboat link. Closing.
