### ISSUE TITLE
Sticky card - image export

### ISSUE THREAD

**Issue by eohammond** [RedHat-UX/red-hat-design-system-site#74]
Style
![image](https://user-images.githubusercontent.com/57179912/95453785-7b383880-0939-11eb-950a-98e609f2c2a8.png)

Footer
![image](https://user-images.githubusercontent.com/57179912/95453832-8db27200-0939-11eb-9d5c-692405c4d3f1.png)

Layout
![image](https://user-images.githubusercontent.com/57179912/95453860-9c008e00-0939-11eb-9707-0223fc679a93.png)

 Content
![image](https://user-images.githubusercontent.com/57179912/95453911-b0448b00-0939-11eb-8891-96150b8309e1.png)

First Best Practice
![image](https://user-images.githubusercontent.com/57179912/95453928-b76b9900-0939-11eb-8ecd-e598987cb507.png)

**Comment by coreyvickery** [comment]
Pull request created.

**Comment by coreyvickery** [comment]
Looks like this was fixed in the most recent Tugboat link. Closing.
