### ISSUE TITLE
Sticky banner - image export

### ISSUE THREAD

**Issue by eohammond** [RedHat-UX/red-hat-design-system-site#75]
Second image under Sizes:
![image](https://user-images.githubusercontent.com/57179912/95454093-f7cb1700-0939-11eb-92e2-ffc6f59f87bf.png)

First image under Placement:
![image](https://user-images.githubusercontent.com/57179912/95454164-103b3180-093a-11eb-9ec5-40803a252348.png)

All Best Practice images

Behavior:
![image](https://user-images.githubusercontent.com/57179912/95454218-23e69800-093a-11eb-8867-57813edce27e.png)

Tablet:
![image](https://user-images.githubusercontent.com/57179912/95454244-306af080-093a-11eb-813b-02bf218371bb.png)

Mobile: 
![image](https://user-images.githubusercontent.com/57179912/95454263-36f96800-093a-11eb-8b89-0bce2a91350c.png)

Mobile portrait:
![image](https://user-images.githubusercontent.com/57179912/95454288-3f51a300-093a-11eb-9584-67de3aa5cf6a.png)

**Comment by coreyvickery** [comment]
Pull request created.

**Comment by coreyvickery** [comment]
Looks like this was fixed in the most recent Tugboat link. Closing.
