### ISSUE TITLE
Disclosure - image export

### ISSUE THREAD

**Issue by eohammond** [RedHat-UX/red-hat-design-system-site#78]
Theme:
![image](https://user-images.githubusercontent.com/57179912/95463069-539b9d00-0946-11eb-91c5-a5df302cc894.png)
![image](https://user-images.githubusercontent.com/57179912/95463042-4bdbf880-0946-11eb-9b3a-8a7bd1d5ec74.png)

Usage:
![image](https://user-images.githubusercontent.com/57179912/95463101-61e9b900-0946-11eb-8598-310280882d46.png)

Usage vs accordion:
![image](https://user-images.githubusercontent.com/57179912/95463126-69a95d80-0946-11eb-90fc-b0e91b4d3a3e.png)

Jump links:
![image](https://user-images.githubusercontent.com/57179912/95463158-70d06b80-0946-11eb-8c68-5feba7609f99.png)

Best practice 2:
![image](https://user-images.githubusercontent.com/57179912/95463184-7928a680-0946-11eb-9fdf-cd71f1e2a06b.png)

Best practice 3:
![image](https://user-images.githubusercontent.com/57179912/95463200-80e84b00-0946-11eb-9a8a-c91d78e072d9.png)

Collapsing and expanding:
![image](https://user-images.githubusercontent.com/57179912/95463229-89408600-0946-11eb-8ab8-78abb9f8b1b0.png)

Tab order:
![image](https://user-images.githubusercontent.com/57179912/95463267-9198c100-0946-11eb-9722-d3cf620d40ae.png)

Desktop, tablet, mobile images all need re-export.

Spacing images need re-export.

**Comment by coreyvickery** [comment]
Pull request created.

**Comment by coreyvickery** [comment]
Looks like this was fixed in the most recent Tugboat link. Closing.
